# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build with .NET

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '*.md'
      - 'docs/*.*'
      - 'LICENSE'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '*.md'
      - 'docs/*.*'
      - 'LICENSE'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: |
        dotnet restore ErpNetFsModel/ErpNetFsModel.csproj
        dotnet restore ErpNetClient/ErpNetClient.csproj
        dotnet restore ErpNetModelDemo/ErpNetModelDemo.csproj
    - name: Build
      run: |
        # List projects explicitly, excluding the one you don't want
        dotnet build ErpNetFsModel/ErpNetFsModel.csproj -c Release
        dotnet build ErpNetClient/ErpNetClient.csproj -c Release
        dotnet build ErpNetModelDemo/ErpNetModelDemo.csproj -c Release
#    - name: Test
#      run: dotnet test --no-build --verbosity normal

